name = "EigenValueSolvers"
uuid = "61c3bbe5-5a69-4256-958a-2912b3f39d32"
version = "0.2.0"
authors = ["Henrik Jakob <jakob@ibb.uni-stuttgart.de> and contributors"]

[workspace]
projects = ["docs"]

[deps]
ArgCheck = "dce04be8-c92d-5529-be00-80e4d2c0e197"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[weakdeps]
ArnoldiMethod = "ec485272-7323-5ecc-a04f-4719b315124d"
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"

[extensions]
EigenValueSolversArnoldiMethodExt = "ArnoldiMethod"
EigenValueSolversArpackExt = "Arpack"
EigenValueSolversKrylovKitExt = "KrylovKit"

[compat]
ArgCheck = "2"
ArnoldiMethod = "0.4"
Arpack = "0.5"
KrylovKit = "0.9.5, 0.10"
LinearAlgebra = "1"
julia = "1.10"

[extras]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["ArnoldiMethod", "Arpack", "DelimitedFiles", "KrylovKit", "SparseArrays", "Test"]
